name = "Cobble Friends"
author = "Minecraft Friends Network"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad6c7a99547ba3c90262f636bfc569bceb7bf15931aeb70f870fc1d9c7923f98"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.188"
