name = "Cobble Friends"
author = "Minecraft Friends Network"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e6afd7445b21943bc75ac08ab58d0fe22ab882b8146f5a70aaee8616601a527"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.188"
