name = "Cobble Friends"
author = "Minecraft Friends Network"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76512ef28427bfe3d2cc25e9a8c3c84469f1c16de6d8af230463dc0c71c80050"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.188"
