name = "Cobble Friends"
author = "Minecraft Friends Network"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5eaf3fcb20423b97ad888ab6d5a98a7c0825defb8231047786143adce0f0ba4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.188"
