name = "Cobble Friends"
author = "Minecraft Friends Network"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b86b7fd26bb965f7ef98517c5613ee13900465acd22ed59efc8e8ab57331b22"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.188"
