name = "Cobble Friends"
author = "Minecraft Friends Network"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f857071d58b406a72f5fcc7418a64b9ecd96c1bd4a39e93b15e0ceefda97233"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.188"
